default_language_version:
  node: system
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.3.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
  - repo: local
    hooks:
      - id: devmoji
        pass_filenames: false
        name: devmoji
        description: run devmoji
        entry: devmoji --edit
        language: node
        additional_dependencies:
          - "devmoji@2.3.0"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6
    hooks:
      - id: clang-format
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v0.3.0
  #   hooks: #mix and match any of the following:
  #     # - id: sbt-fatal-warnings #arguments optional
  #     #   args: [--scope=test:compile]
  #     # - id: sbt-unused-imports #includes fatal warnings, arguments optional
  #     #   args: [--scope=test:compile]
  #     - id: sbt-scalafmt
  #     # - id: sbt-wartremover #arguments are optional
  #     #   args: [--warts=Warts.unsafe, --scope=test:compile]
