default_language_version:
  node: system
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.3.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6
    hooks:
      - id: clang-format
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: devmoji
        pass_filenames: false
        name: devmoji
        description: run devmoji
        entry: devmoji --edit
        language: node
        additional_dependencies:
          - "devmoji@2.3.0"
  - repo: local
    hooks:
      - id: verible-verilog-format
        name: verible-verilog-format
        description: run verible-verilog-format
        entry: verible-verilog-format --inplace
        args: [
          "--assignment_statement_alignment=align",
          "--case_items_alignment=align",
          "--class_member_variable_alignment=align",
          "--distribution_items_alignment=align",
          "--enum_assignment_statement_alignment=align",
          "--formal_parameters_alignment=align",
          "--module_net_variable_alignment=align",
          "--named_parameter_alignment=align",
          "--named_port_alignment=align",
          "--port_declarations_alignment=align",
          "--struct_union_members_alignment=align",
        ]
        language: system
        types: [file]
        files: \.(sv|svh)$
  - repo: local
    hooks:
      - id: scalafmt
        name: scalafmt
        description: run scalafmt
        entry: scalafmt
        language: system
        types: [file]
        files: \.scala$
